In [29]:
import numpy as np
import pandas as pd
from IPython.display import display, HTML

pd.set_option('display.precision', 1)
df_left = pd.DataFrame({'색': ['red','orange','yellow','green','blue'],
                        '가격': [1000,2000,3000,4000,5000]},
                       index=[9,1,2,3,4]
                      )
    
df_right = pd.DataFrame({'색': ['yellow','green','blue','navy','purple'],
                        '이름': ['노랑','초록','파랑','남색','보라']},
                       index=[3,4,5,6,7]
                      )

#예제 concat
df_concat = pd.concat([df_left, df_right])
print('\ndf_concat no option')
display(df_concat)

df_concat = pd.concat([df_left, df_right], ignore_index=True)
print('\ndf_concat ignore_index=True')
display(df_concat)

df_concat2 = pd.concat([df_left, df_right], axis=1)
print('\ndf_concat axis=1')
display(df_concat2)

df_concat3 = pd.concat([df_left, df_right], axis=1, ignore_index=True)
print('\ndf_concat axis=1, ignore_index=True')
display(df_concat3)

df_left.reset_index(drop=True, inplace=True)
df_right.reset_index(drop=True, inplace=True)
df_left.rename(columns={'색':'색_left'}, inplace=True)
df_right.rename(columns={'색':'색_right'}, inplace=True)
df_concat4 = pd.concat([df_left, df_right], axis=1)
print('\ndf_concat reset_index, rename_column, axis=1')
display(df_concat4)

print('\nside by side')
display(HTML('<div style="display: flex"><div><p>left:</p>{}</div><div style="margin-left: 20px"><p>right:</p>{}</div></div>'.format(
df_left.to_html(), df_right.to_html())))

df_left.rename(columns={'색_left':'색'}, inplace=True)
df_right.rename(columns={'색_right':'색'}, inplace=True)

#예제 inner join
df_inner = pd.merge(df_left, df_right, how="inner", on="색")
print('\ndf_inner')
display(df_inner)

#예제 outer join
df_outer = pd.merge(df_left, df_right, how="outer", on="색")
print('\ndf_outer')
display(df_outer)

#예제 left join
df_left = pd.merge(df_left, df_right, how="left", on="색")
print('\ndf_left')
display(df_left)

#예제 right join
df_right = pd.merge(df_left, df_right, how="right", on="색")
print('\ndf_right')
display(df_right)

#예제 index join 인덱스로 join 하며 컬럼 이름이 같은 경우 _x, _y 로 컬럼명이 바뀌어 표시된다.
df_right_index = pd.merge(df_left, df_right, left_index=True, right_index=True, how="right")
print('\ndf_right_index')
display(df_right_index)

#예제 데이터프레임의 join 을 사용. 
df_left2 = pd.DataFrame({'색_left': ['red','orange','yellow','green','blue'],
                        '가격': [1000,2000,3000,4000,5000]},
                       index=[9,1,2,3,4]
                      )
display(df_left2)
df_right2 = pd.DataFrame({'색_right': ['yellow','green','blue','navy','purple'],
                        '이름': ['노랑','초록','파랑','남색','보라']},
                       index=[3,4,5,6,7]
                      )
display(df_right2)
#
df_left_join_right = df_left2.join(df_right2, how="right")
print('\ndf_left.join(df_right, how=right)')
display(df_left_join_right)

df_concat no option

        색      가격   이름
9     red  1000.0  NaN
1  orange  2000.0  NaN
2  yellow  3000.0  NaN
3   green  4000.0  NaN
4    blue  5000.0  NaN
3  yellow     NaN   노랑
4   green     NaN   초록
5    blue     NaN   파랑
6    navy     NaN   남색
7  purple     NaN   보라

df_concat ignore_index=True

        색      가격   이름
0     red  1000.0  NaN
1  orange  2000.0  NaN
2  yellow  3000.0  NaN
3   green  4000.0  NaN
4    blue  5000.0  NaN
5  yellow     NaN   노랑
6   green     NaN   초록
7    blue     NaN   파랑
8    navy     NaN   남색
9  purple     NaN   보라

df_concat axis=1

        색      가격       색   이름
9     red  1000.0     NaN  NaN
1  orange  2000.0     NaN  NaN
2  yellow  3000.0     NaN  NaN
3   green  4000.0  yellow   노랑
4    blue  5000.0   green   초록
5     NaN     NaN    blue   파랑
6     NaN     NaN    navy   남색
7     NaN     NaN  purple   보라

df_concat axis=1, ignore_index=True

        0       1       2    3
9     red  1000.0     NaN  NaN
1  orange  2000.0     NaN  NaN
2  yellow  3000.0     NaN  NaN
3   green  4000.0  yellow   노랑
4    blue  5000.0   green   초록
5     NaN     NaN    blue   파랑
6     NaN     NaN    navy   남색
7     NaN     NaN  purple   보라

df_concat reset_index, rename_column, axis=1

   색_left    가격 색_right  이름
0     red  1000  yellow  노랑
1  orange  2000   green  초록
2  yellow  3000    blue  파랑
3   green  4000    navy  남색
4    blue  5000  purple  보라

side by side

df_inner

        색    가격  이름
0  yellow  3000  노랑
1   green  4000  초록
2    blue  5000  파랑

df_outer

        색      가격   이름
0    blue  5000.0   파랑
1   green  4000.0   초록
2    navy     NaN   남색
3  orange  2000.0  NaN
4  purple     NaN   보라
5     red  1000.0  NaN
6  yellow  3000.0   노랑

df_left

        색    가격   이름
0     red  1000  NaN
1  orange  2000  NaN
2  yellow  3000   노랑
3   green  4000   초록
4    blue  5000   파랑

df_right

        색      가격 이름_x 이름_y
0  yellow  3000.0   노랑   노랑
1   green  4000.0   초록   초록
2    blue  5000.0   파랑   파랑
3    navy     NaN  NaN   남색
4  purple     NaN  NaN   보라

df_right_index

      색_x  가격_x   이름     색_y    가격_y 이름_x 이름_y
0     red  1000  NaN  yellow  3000.0   노랑   노랑
1  orange  2000  NaN   green  4000.0   초록   초록
2  yellow  3000   노랑    blue  5000.0   파랑   파랑
3   green  4000   초록    navy     NaN  NaN   남색
4    blue  5000   파랑  purple     NaN  NaN   보라

   색_left    가격
9     red  1000
1  orange  2000
2  yellow  3000
3   green  4000
4    blue  5000

  색_right  이름
3  yellow  노랑
4   green  초록
5    blue  파랑
6    navy  남색
7  purple  보라

df_left.join(df_right, how=right)

  색_left      가격 색_right  이름
3  green  4000.0  yellow  노랑
4   blue  5000.0   green  초록
5    NaN     NaN    blue  파랑
6    NaN     NaN    navy  남색
7    NaN     NaN  purple  보라